### ISSUE TITLE
add_dirs_and_files_icons() accidentally discards 'open_with' argument.

### ISSUE THREAD

**Issue by ewhac** [terceiro/awesome-freedesktop#17]
Saw this right away when I looked at desktop.lua wondering why desktop icons weren't working:

``` lua
function add_dirs_and_files_icons(arg)
    arg.open_with = arg.open_width or 'thunar'
```

Note that it's testing against 'open_wi_d_th' and not 'open_with'.

**Comment by terceiro** [comment]
Hi,

This project has been taken over by [@copycat-killer](https://github.com/copycat-killer). Please use the fork [over there](https://github.com/copycat-killer/awesome-freedesktop) instead.

if this issue still applies to @copycat-killer's fork, please open an issue there.
