### ISSUE TITLE
Speed up icon lookup

### ISSUE THREAD

**Issue by mrzechonek** [terceiro/awesome-freedesktop#19]
If you have http://github.com/pavouk/lgi, icon lookup can be much, much faster:

<pre>
diff --git a/freedesktop/utils.lua b/freedesktop/utils.lua
index 6980291..7280d80 100644
--- a/freedesktop/utils.lua
+++ b/freedesktop/utils.lua
@@ -7,11 +7,15 @@ local type = type
 local ipairs = ipairs
 local pairs = pairs
 
+local lgi = require('lgi')
+local Gtk = lgi.require('Gtk')
+
 module("freedesktop.utils")
 
 terminal = 'xterm'
 
 icon_theme = nil
+local gtk_icon_theme = Gtk.IconTheme.get_default()
 
 all_icon_sizes = {
     '48x48',
@@ -55,6 +59,14 @@ function lookup_icon(arg)
         -- icons with absolute path and supported (AFAICT) formats
         return arg.icon
     else
+        local gtk_icon_info = Gtk.IconTheme.lookup_icon(gtk_icon_theme, arg.icon, 48, 0)
+        if gtk_icon_info then
+            filename = Gtk.IconInfo.get_filename(gtk_icon_info)
+            if filename then
+                return filename
+            end
+        end
+
         local icon_path = {}
         local icon_themes = {}
         local icon_theme_paths = {}
</pre>

**Comment by terceiro** [comment]
Hi,

This project has been taken over by [@copycat-killer](https://github.com/copycat-killer). Please use the fork [over there](https://github.com/copycat-killer/awesome-freedesktop) instead.

if this issue still applies to @copycat-killer's fork, please open an issue there.
