### ISSUE TITLE
Lua 5.2 Compatibility

### ISSUE THREAD

**Issue by ILMostro** [terceiro/awesome-freedesktop#23]
According to `awesome`'s [wiki page and/or changelog of latest versions](http://awesome.naquadah.org/wiki/Awesome_3.4_to_3.5#Lua_5.2_Compatibility)

> **In Lua 5.2, the _module()_ function was deprecated. This has an effect on user configs. You now have to explicitely assign modules to variables when you load them:**

[`module("freedesktop.desktop")`](https://github.com/terceiro/awesome-freedesktop/blob/master/freedesktop/desktop.lua#L11) in `desktop.lua`, and [`module("freedesktop.menu")`](https://github.com/terceiro/awesome-freedesktop/blob/master/freedesktop/menu.lua#L10) in `menu.lua` should reflect that.

**Comment by copycat-killer** [comment]
@ILMostro Check [this](https://github.com/copycat-killer/awesome-freedesktop).

**Comment by terceiro** [comment]
Hi,

This project has been taken over by [@copycat-killer](https://github.com/copycat-killer). Please use the fork [over there](https://github.com/copycat-killer/awesome-freedesktop) instead.

if this issue still applies to @copycat-killer's fork, please open an issue there.
