### ISSUE TITLE
widget module DEPRACATED

### ISSUE THREAD

**Issue by ILMostro** [terceiro/awesome-freedesktop#25]
According to the `awesome` logs

```
    DEPRECATED: The widget module is deprecated.  Please consider using the sdk/ui module instead.
```

**Comment by terceiro** [comment]
Hi,

This project has been taken over by [@copycat-killer](https://github.com/copycat-killer). Please use the fork [over there](https://github.com/copycat-killer/awesome-freedesktop) instead.

if this issue still applies to @copycat-killer's fork, please open an issue there.
