### ISSUE TITLE
static definition of categories should probably be dynamic

### ISSUE THREAD

**Issue by lkraav** [terceiro/awesome-freedesktop#3]
https://github.com/terceiro/awesome-freedesktop/blob/master/freedesktop/menu.lua#L24
https://github.com/terceiro/awesome-freedesktop/blob/master/freedesktop/menu.lua#L63

is there a particular reason for static definition of menus instead of inserting them on-demand as we discover respectively belonging menuitems?

**Comment by terceiro** [comment]
Hi,

This project has been taken over by [@copycat-killer](https://github.com/copycat-killer). Please use the fork [over there](https://github.com/copycat-killer/awesome-freedesktop) instead.

if this issue still applies to @copycat-killer's fork, please open an issue there.
