### ISSUE TITLE
'desktop' module is broken.

### ISSUE THREAD

**Issue by ticki** [terceiro/awesome-freedesktop#31]
A workaround is to not include the desktop module in your `rc.lua`. This is only a temporary fix, though.

**Comment by copycat-killer** [comment]
@ticki Check [this](https://github.com/copycat-killer/awesome-freedesktop).

**Comment by terceiro** [comment]
Hi,

This project has been taken over by [@copycat-killer](https://github.com/copycat-killer). Please use the fork [over there](https://github.com/copycat-killer/awesome-freedesktop) instead.

if this issue still applies to @copycat-killer's fork, please open an issue there.
