### ISSUE TITLE
Wrong name for Clementine

### ISSUE THREAD

**Issue by daks-ua** [terceiro/awesome-freedesktop#6]
media-sound/clementine installs /usr/share/applications/clementine.desktop:

[Desktop Entry]
Version=1.0
Type=Application
Name=Clementine
GenericName=Clementine Music Player
GenericName[pt]=Reprodutor de músicas Clementine
Comment=Plays music and last.fm streams
Comment[pt]=Reprodução de músicas e emissões last.fm
Exec=clementine
TryExec=clementine
Icon=application-x-clementine
Terminal=false
Categories=AudioVideo;Player;Qt;
StartupNotify=false
MimeType=application/ogg;application/x-ogg;application/x-ogm-audio;audio/aac;audio/mp4;audio/mpeg;audio/mpegurl;audio/ogg;audio/vnd.rn-real
X-Ayatana-Desktop-Shortcuts=Play;Pause;Stop;Previous;Next;
...
bla-bla-bla
...
[Previous Shortcut Group]
Name=Previous
Exec=clementine --previous
TargetEnvironment=Unity

[Next Shortcut Group]
Name=Next
Exec=clementine --next
TargetEnvironment=Unity

Awesome-freedesktop place Clementine into the menu with the last Name tag - "Next" taken from [Next Shortcut Group] section (even if this section is commented out). But it should take Name from [Desktop Entry] section, not from last one.
Thanks.

**Comment by terceiro** [comment]
Hi,

This project has been taken over by [@copycat-killer](https://github.com/copycat-killer). Please use the fork [over there](https://github.com/copycat-killer/awesome-freedesktop) instead.

if this issue still applies to @copycat-killer's fork, please open an issue there.
